global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['app:8001']
  
  - job_name: 'jenkins'
    static_configs:
      - targets: ['YOUR_DROPLET_IP:8080']
    metrics_path: '/prometheus/'
